view distillation design doc
TheDataStation/ver pull request #7
Opened 2022-11-10 04:14 UTC by youny626

2022-11-10 19:24 UTC, raulcf reviewed
is the summarization strategy a first-class object of this interface? it may need to be, in which case, that should be reflected in the design.

2022-11-10 19:24 UTC, raulcf commented on view_distillation/design_doc.md
> +`result = vd.prune_compatible_views()`
a better name would suggest what the summarization operation does, e.g., reduce_compatible_views_to_one()

the pruning aspect is implicit in the operation, but this name explains how the pruning is done

2022-11-10 19:24 UTC, raulcf commented on view_distillation/design_doc.md
> +`result = vd.find_compatible_views()`
typo, this is contained views

2022-11-10 19:24 UTC, raulcf commented on view_distillation/design_doc.md
> +This will return a list of lists, each inner list contains the set of views in sorted order (descending by view size)
confusing use of list and set:

- First, why is the first list a list and not a set? 
- Second, the "inner list returns a set of views sorted" does not make sense. If it's sorted it is a list, not a set, right?

2022-11-10 19:24 UTC, raulcf commented on view_distillation/design_doc.md
> +where each view contains all the following views.
what is "following view"

it is important to spend time thinking carefully how we are explaining these APIs to the world

2022-11-10 19:24 UTC, raulcf commented on view_distillation/design_doc.md
> +`result = vd.prune_contained_views()`
as above, the pruning is not clear. it is better if it is obvious. if there are multiple summarization strategies, those could be given as a parameter (even if we only implement one now)

2023-02-06 16:06 UTC, raulcf requested changes
All functionality seems concentrated in a utils.py. This is not a very good design. Separate the main logic of the module from the real "utils". I'll take a look at the PR after.

2023-02-06 16:06 UTC, raulcf commented on view_distillation/code_used_for_paper/utils.py
> +import random
this utils.py is in a folder "code_used_for_paper" -- can you refactor this asap?

2023-02-06 16:06 UTC, raulcf commented on view_distillation/code_used_for_paper/utils.py
> +    # df = df.astype(str).apply(lambda x: x.str.strip().str.lower())
clean up commented out code

2023-02-06 16:06 UTC, raulcf commented on view_distillation/code_used_for_paper/utils.py
> +def create_contradictory_signals(path_to_df_dict,
are all these functions used? would be good to verify that is the case

2023-02-06 17:27 UTC, youny626 commented
> All functionality seems concentrated in a utils.py. This is not a very good design. Separate the main logic of the module from the real "utils". I'll take a look at the PR after.

@raulcf I think you are looking at the wrong file. I am not using utils.py(or anything else) from code_used_for_paper/. The new module only uses utils.py and view_distillation.py under the current view_distillation directory. Documentations are in README.

2023-02-06 17:37 UTC, closed without merging